# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f2bb80efa69cd313c3e267a0b79756e431625b916a58e69a97e0aee4fbd25cd0aa8f8323a00234d859d0cbcc8195c17c3066dfed25d3a371223100758f46523

test:
  secret_key_base: 272e383d81d50d966274d2610ec7a89fb1ceadb99a9bd0f0af18f8f2f6a00df035a2adff1d22cfa0c46dd2ee12e444f1b555c6e355ef9bc79986539c9ad32b6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
